version: "3.7"

services:
  postgres:
    image: postgres
    networks:
      - web
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    logging:
      driver: "none"
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres:
networks:
    web: